### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by dayanageeks** [Moyrasc/Todolist-Application-Using-React-and-Fetch#1]
- [x]  AL pintar la lista de tareas  el valor de la X   ponle estilo con css para que aparezca la manita que se puede clickar, para experiencia de usuario es  mejor https://github.com/Moyrasc/Todolist-Application-Using-React-and-Fetch/blob/main/src/js/component/taskList.jsx#L128 
- [x]  Cambia la tipografía para que sea mas legible

**Comment by Moyrasc** [comment]
He modificado el tipo de letra y añadido el cursor pointer.
